
---
- name: Install k8s
  hosts: 
    - masters
    - workers
  roles:
    - k8s
  tags:
    - k8s

- name: Install kafka
  hosts:
    - kafka
  roles:
    - kafka
  tags:
    - kafka

- name: Install prometheus
  hosts:
    - masters
  roles:
    - prometheusGrafana
  tags:
    - prometheus

- name: Install project
  hosts:
    - masters
  roles:
    - chart
  tags:
    - project


  
