---
- name: Download Kafka and Unzip 
  become: yes
  become_user: root
  unarchive:
    src: https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz
    dest: "{{installation_dir}}"
    mode: 0755
    remote_src: yes
- name: Move all the files to parent Directory
  become: yes    
  shell:
      mv {{installation_dir}}/kafka_*/* {{installation_dir}}/.
  ignore_errors: yes

