---
- name: Create input topic
  shell: "{{ installation_dir }}/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic input --partitions 1 --replication-factor 1 --config max.message.bytes=64000 --config flush.messages=1"
  tags: 
    - input
  
  

- name: Create output topic
  shell: "{{ installation_dir }}/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic output --partitions 1 --replication-factor 1 --config max.message.bytes=64000 --config flush.messages=1"
  tags:
    - output
