apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.grafana.name }}
  namespace: {{ .Values.service.grafana.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grafana.port }}
      targetPort: {{ .Values.service.grafana.targerPort}}
      protocol: TCP
      name: {{ .Values.service.grafana.name}}
      nodePort: {{ .Values.service.grafana.nodePort}}
  selector:
    {{- include "tpl.selectorLabelsGrafana" . | nindent 4 }}


